### ISSUE TITLE
When I try to create a new post

### ISSUE THREAD

**Issue by efrapp** [keshav-c/members-only#4]
When I try to create a new post, I get this error:

<img width="904" alt="Screen Shot 2019-09-10 at 4 38 12 PM" src="https://user-images.githubusercontent.com/698811/64652483-990b3500-d3e9-11e9-9814-3eba328d64dd.png">

**Comment by keshav-c** [comment]
Fixed in commit [d4ea2e](https://github.com/keshav-c/members-only/commit/dd4ea2e879733a556727b3d3e61455fe7334c35e)
